### ISSUE TITLE
Clip exporting naming scheme is unclear

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#166]
When I export clips, they go into a Folder called `Clips`. However, from there they go into separate folders, and then are exported as .wav files with names following this schema: "Clip 000 364 459.wav". 

It isn't clear to me why this happens, and it makes it hard to identify clips and to know where they come from. Could we export them with their time and date signature?

As well, is it possible to export clips with a longer time period? I would like to have clips that have at least 2 seconds of audio on each side of the call, to make it easier for the ear to adjust to the call when playing it.

**Comment by HaroldMills** [comment]
If you export clips using Vesper's `Export clips to audio files` command, in the `File` dropdown, they should be written to the folder you specify in the command form, to files with names of the form `<station>_<mic>_<detector>_<start time>.wav`.

It sounds like you might have run the `Create clip audio files` command, in the `Admin` dropdown. That command and the companion `Delete clip audio files` command are for managing a cache of clip files that Vesper can grab clip samples from instead of extracting them from recordings. The cached files are not for (direct) user consumption, and have names like the one you referred to. I'll consider removing these commands from the default UI to avoid the potential for confusion, since most people don't need them.

It is currently not possible to export clips with durations other than the clip durations. That issue has come up before, though, so I've created #167 for it.

**Comment by RichardLitt** [comment]
> I'll consider removing these commands from the default UI to avoid the potential for confusion, since most people don't need them.

This sounds like a good move, to me. I was able to export clips with useful naming using the File dropdown. 

Would it be possible to add an option to export clips with names for the users current timezone? Matching these clips to my eBird checklists is arduous if I have to keep adding five hours.

**Comment by HaroldMills** [comment]
I am splitting this issue into #167 and #172.
