### ISSUE TITLE
Add a way to switch between coarse and call classifiers quickly

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#171]
Often, I'll mistype while classifying birds manually - for instance, I'll type 'N' meaning 'Next', and it'll label it as 'NOWA'. Then, I need to go and click the dropdown, switch classifiers to 'Course', type 'C', and then click the dropdown again in order to make it go back to the Calls classifier. 

It'd be great if I could have a way to switch easily, so that I can use a keystroke to classify something as a 'Noise' or 'Call' using the Coarse classifier without having to go through this process.

**Comment by HaroldMills** [comment]
This issue is addressed by d58095be63ac9f3d928ea1db0341cdb81582cf65, which adds clip album commands for changing clip album presets. The commands are `set_clip_album_settings_preset` and `set_clip_album_commands_preset`, and both take a single argument, the name of a preset. So, for example if you have two `Clip Album Commands` presets called `Coarse` and `Calls`, you can add:

        "$": [set_clip_album_commands_preset, Calls]

to the `Coarse` preset and:

        "$": [set_clip_album_commands_preset, Coarse]

to the `Calls` preset. This makes it easy to switch between the two presets, since you can just type "$" when either preset is active to switch to the other. Of course, you can bind the commands to any key you wish: it doesn't have to be the "$" key.

**Comment by RichardLitt** [comment]
Thank you!
