### ISSUE TITLE
Link to discussion group?

### ISSUE THREAD

**Issue by tve** [HaroldMills/Vesper#187]
I'm interested in Vesper and am failing to find a forum to ask newbie questions in. Is there such a group/forum? I'm aware of the NFC facebook group, but the volume of messages there doesn't seem conducive to talking about vesper. Plus, I do everything in my power to avoid FB!
NB: maybe enabling the discussions feature on this repo is a simple solution?

**Comment by JGyekis** [comment]
If it's really basic stuff, I'm a good resource for beginner level things. I won't fix real technical problems, but I have instructions for setup steps in a Google Drive https://drive.google.com/drive/folders/15qyJf0iuiwGROlDY3LzM6pQISPfXdQYp?usp=sharing and also there's a nice video introducing Vesper you can find linked in the doc here https://docs.google.com/document/d/1YaKaqGodIJnhLMBfQTJAxRnk9Cb4qoE4H1syjpL1Otg/edit?usp=sharing

**Comment by HaroldMills** [comment]
Thanks for writing, Thorsten, and for your pointers, Joe. I agree that a better forum for communication among Vesper users would be good. I think a simple email list would probably be best, since email is a tool almost everybody is already familiar with. Some of the people who need to be involved in discussions about setting that up are traveling a fair amount this month, but I'll aim to set something up when that travel has passed. In the mean time, I'm happy to email directly with you. You can reach me at my full name at Gmail.

**Comment by RichardLitt** [comment]
Isn't there also a Slack Group with MPG Ranch?

**Comment by HaroldMills** [comment]
Yes, but the person who signs people up for that is out of town. I like the idea of a public forum that anybody can look at and sign up for themselves.

**Comment by HaroldMills** [comment]
@tve, there is now a vesper-users Google Group, in case you might still be interested.
