### ISSUE TITLE
Tracking analysis of recordings

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#209]
Currently, I record intermittently. Sometimes I stop recording for a few nights for a variety of reasons (rain, going out of town, etc). Occasionally, I record NFCs while listening live, which has different ramifications for how to log birds on eBird. I note down when I record, when the twilight times are, and what times I listen live in a document. Then, I import the audio into Vesper, and detect and classify using Vesper. Sometimes, I'll go through and classify NFCs manually, but most nights I don't. When I classify them manually, occasionally I'll export that night or the hours I classified as a csv, and then I'll import them automatically into eBird, using different accounts for time I listened live or for times that I was just recording automatically.  Sometimes I'll also go through the audio file manually and look for things that Vesper missed, like shorebirds or owls. 

There's currently no way for me to track all of this metadata on Vesper. I use a text file, and include information like this:

```

## August 23, 2022

Recorded correct times: Yes.
Recorded time: Yes.
Recorded automatically: Yes.
Copied to HD: Yes.
Analyzed: Yes.
Manually analyzed: No.
Listened Live: Yes, astronomical twilight.
Logged on eBird: Yes.
Logged highlights on iNat: No.
Notes: No birds of interest.
```

However, this isn't ideal - I can't visualize what nights I've already analyzed or not, and I can't see automatically if I have uploaded them to eBird, and I don't have a way to list those eBird checklists or iNat entries I created.

I've debated building my own CRUD app to enable me to track this online, so that I can access the data without having to go into my recording folders every time. However, I wonder if this data should live closer to the source - and perhaps in Vesper. 

@HaroldMills, how do you track this?

**Comment by HaroldMills** [comment]
I use a spreadsheet, usually one for each migration season. There's a row for each night of the season, and columns mostly for counts of various types of detection and call counts. I include a comments column for more free-form data.

The MPG Ranch folks used spreadsheets to keep track of the analysis of their recordings. Their workflow included various tasks to be performed for each recording, and whenever somebody performed a task for a particular recording they would check it off in the spreadsheet.

Issue #76 relates to this. It dates from early in the Vesper project, and not much has happened with it since spreadsheets have provided a reasonable if not ideal solution.

That said, one of my main motivations for writing Vesper was to create a system that could keep track of connections between recordings and the metadata (clips, annotations, etc.) created from them, so that less of that burden would fall on users. Along those lines, I am considering supporting annotations and tags for recordings and perhaps other objects instead of just for clips. I also would like to support comment threads for clips and recordings and perhaps other objects. I think that those features, perhaps combined with a customizable tabular metadata display (but then you're getting into spreadsheet territory, and I don't want to go very far into that) could go a long way towards allowing people to track their analysis more fully within Vesper.
