### ISSUE TITLE
Running Nighthawk in Docker/Compose

### ISSUE THREAD

**Issue by alhirzel** [HaroldMills/Vesper#220]
Is there any available guidance for running Nighthawk within the docker-compose development environment? I am not yet familiar with the auto-detection logic that is being used to call from Vesper to Nighthawk, and so I am not sure how to make it work within the containers.

**Comment by HaroldMills** [comment]
Eventually you'll be able to run Nighthawk in a Docker container and Vesper will be able to use it via a web API. That is not implemented yet, however, and there are other substantial tasks in my queue that I'll need to work on first, so unfortunately it won't happen very soon. You might be able to kludge up a Docker image that includes both Vesper and Nighthawk so that Vesper can invoke Nighthawk within the same container, but that's not good Docker practice.

**Comment by alhirzel** [comment]
I believe I have successfully constructed such an amalgam. Thanks for the hints, and your work, @HaroldMills!
